# Khmer Digits OCR Model Configuration

model:
  name: "khmer_digits_ocr"
  architecture: "cnn_rnn_attention"
  
  # Input specifications
  input:
    image_size: [128, 64]  # [width, height]
    channels: 3  # RGB
    normalization:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  
  # Character set
  characters:
    khmer_digits: ["០", "១", "២", "៣", "៤", "៥", "៦", "៧", "៨", "៩"]
    special_tokens: ["<EOS>", "<PAD>", "<BLANK>"]
    total_classes: 13
    max_sequence_length: 8
  
  # CNN Backbone
  cnn:
    type: "resnet18"  # or "efficientnet-b0"
    pretrained: true
    feature_size: 512
  
  # RNN Components
  rnn:
    encoder:
      type: "bidirectional_lstm"
      hidden_size: 256
      num_layers: 2
      dropout: 0.1
    
    decoder:
      type: "lstm"
      hidden_size: 256
      num_layers: 1
      dropout: 0.1
    
    attention:
      type: "bahdanau"
      hidden_size: 256

# Training configuration
training:
  batch_size: 32
  num_epochs: 100
  learning_rate: 1e-3
  weight_decay: 1e-4
  
  optimizer:
    type: "adamw"
    lr_scheduler:
      type: "cosine_annealing"
      t_max: 100
  
  loss:
    type: "cross_entropy"
    sequence_penalty: 0.1
  
  early_stopping:
    patience: 10
    min_delta: 1e-4

# Data configuration
data:
  dataset_size: 15000
  train_split: 0.8
  val_split: 0.2
  
  augmentation:
    rotation: [-15, 15]
    scaling: [0.8, 1.2]
    noise:
      gaussian_std: 0.01
    brightness: [-0.2, 0.2]
    contrast: [-0.2, 0.2]

# Paths
paths:
  fonts_dir: "src/fonts"
  data_dir: "generated_data"
  models_dir: "models"
  logs_dir: "logs" 